spring:
  rsocket:
    server:
      port: 6565
#      ssl:
#        enabled: true
#        key-store-type: PKCS12
#        key-store: /Users/mysend/workspace/socket-study/ssl-tls/rsocket-server.p12
#        key-store-password: password
#        key-alias: rsocket